# Generated by Django 3.1 on 2023-06-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0004_auto_20180315_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='extra',
            field=models.JSONField(blank=True, null=True, verbose_name='JSONField to store addtional data'),
        ),
    ]